"""Infer a part category from its name and description by keyword scoring.

The crawler uses this when no category is given; it returns a `PART_CATEGORIES`
name, or "other" when no category scores above `MIN_SCORE`.
"""

import re
from typing import Optional

CATEGORY_KEYWORDS: dict[str, list[str]] = {
    "exhaust": [
        "exhaust",
        "muffler",
        "header",
        "headers",
        "downpipe",
        "down pipe",
        "cat-back",
        "catback",
        "axle-back",
        "axle back",
        "midpipe",
        "mid pipe",
        "tip",
        "exhaust tip",
        "resonator",
        "resonated",
        "non-resonated",
        "y-pipe",
        "x-pipe",
        "turbo back",
        "touring edition",
        "track edition",
        "conversion kit",
        "hi-power",
        "hi power",
        "metal catalyzer",
        "catalytic converter",
        "front pipe",
        "center pipe",
        "legamax",
        "super sound master",
        "exhaust manifold",
        "cel fix",
        "high flow cat",
        "race pipe",
        "rear section",
    ],
    "suspension": [
        "coilover",
        "coilovers",
        "coil over",
        "coil-over",
        "spring",
        "springs",
        "strut",
        "struts",
        "shock",
        "shocks",
        "sway bar",
        "swaybar",
        "stabilizer",
        "control arm",
        "camber",
        "lowering",
        "lowered",
        "bushing",
        "bushings",
        "end link",
        "tie rod",
        "tie rods",
        "trailing arm",
        "rear trailing arm",
        "chassis brace",
        "power brace",
        "brace bar",
        "underbody",
        "subframe brace",
        "chassis",
        "front brace",
        "rear brace",
        "damping",
        "damping delete",
        "electronic damping",
        "electronic damping delete",
        "error canceller",
        "hipermax",
        "performance damper",
        "carbon brace",
        "front lower bar",
        "lower arm bar",
        "tein s.tech",
        "eibach pro-kit",
        "eibach pro kit",
        "bump stop",
        "pillowball",
        "error canceler",
        "suspension error",
    ],
    "engine": [
        "turbo",
        "turbocharger",
        "supercharger",
        "intake",
        "cold air",
        "cai",
        "air filter",
        "intercooler",
        "blow-off",
        "bov",
        "wastegate",
        "tune",
        "ecu",
        "piggyback",
        "obd",
        "obd2",
        "obdii",
        "flash adapter",
        "flash tuning",
        "downpipe",
        "header",
        "injector",
        "injectors",
        "fuel injector",
        "fuel pump",
        "fuel line",
        "lpfp",
        "oil cooler",
        "oil cap",
        "fluid cap",
        "reservoir cap",
        "radiator",
        "charge pipe",
        "chargepipe",
        "catch can",
        "coolant",
        "auxiliary radiator",
        "engine cover",
        "valve cover",
        "rocker cover",
        "dme",
        "fuel pressure",
        "fuel pressure gauge",
        "ignition coil",
        "coil pack",
        "spark plug",
        "boost tap",
        "vacuum line",
        "vacuum tubing",
        "tubing kit",
        "charge air",
        "trans cooler",
        "dct cooler",
        "transmission cooler",
        "throttle booster",
        "engine bay",
        "oil change",
        "oil change kit",
        "pre-filter",
        "prefilters",
        "filter replacement",
        "intake muffler",
        "intake resonator",
        "connecting rod",
        "rod set",
        "washer fluid",
        "washer fluid cap",
        "retaining kit",
        "piston",
        "pistons",
        "piston ring",
        "i-beam",
        "h-beam",
        "head gasket",
        "gasket set",
        "oil pump",
        "oil pan",
        "oil drain",
        "oil feed",
        "camshaft",
        "camshafts",
        "cam gear",
        "cam sprocket",
        "timing chain",
        "timing belt",
        "timing kit",
        "tensioner",
        "valve spring",
        "valve springs",
        "valve retainer",
        "valve retainers",
        "valve seat",
        "valve guide",
        "pushrod",
        "lifter",
        "rocker arm",
        "main bearing",
        "rod bearing",
        "cam bearing",
        "crankshaft",
        "crank pulley",
        "cylinder head",
        "block",
        "head stud",
        "head studs",
        "main stud",
        "main studs",
        "rod stud",
        "rod studs",
        "nitrous",
        "water methanol",
        "silicone hose",
        "coupler",
        "t-bolt clamp",
        "an fitting",
        "hose end",
        "-3an",
        "-4an",
        "-6an",
        "-8an",
        "-10an",
        "-12an",
        "-16an",
        "npt",
        "orb fitting",
        "hose barb",
        "adapter fitting",
        "fitting flare",
        "banjo fitting",
        "union fitting",
        "engine mount",
        "motor mount",
        "trans mount",
        "transmission mount",
        "swap mount",
        "swap mounts",
        "engine bracket",
        "fuel rail",
        "fuel filter",
        "fuel tank",
        "fuel feed",
        "fuel return",
        "fuel line",
        "valve seat",
        "valve guide",
        "cam gear",
        "throttle body",
        "turbine housing",
        "compressor housing",
        "chra",
        "super core",
        "wastegate actuator",
        "actuator upgrade",
        "v-band clamp",
        "vband clamp",
        "v-band flange",
        "vband flange",
        "v-band entry",
        "v-band exit",
        "tial",
        "garrett",
        "turbosmart",
        "turbine inlet",
        "turbine outlet",
        "compressor inlet",
        "compressor outlet",
        "wastegate",
        "hose union",
        "hose band",
        "hose clamp",
        "hose nipple",
        "vacuum tube",
        "swivel nipple",
        "swivel barbed",
        "barbed nipple",
        "vacuum nipple",
        "plug bolt union",
        "compression tube",
        "bend pipe",
        "straight pipe",
        "cast aluminum elbow",
        "aluminum bend",
        "t-bolt clamp",
        "t bolt clamp",
        "an-3",
        "an-4",
        "an-6",
        "an-8",
        "an-10",
        "an-12",
        "an-16",
        "banjo bolt",
        "metric adapter",
        "tube sleeve",
        "tube nut",
        "bulkhead fitting",
        "bulkhead nut",
        "thread sealant",
        "fitting elbow",
        "elbow fitting",
        "racing suction",
        "premium suction",
        "power flow",
        "airinx",
        "drycarbon suction",
        "suction return",
        "suction kit",
        "airbox",
        "air box",
        "airflow",
        "maf hose",
        "map sensor",
        "throttle position sensor",
        "knock sensor",
        "o2 sensor",
        "wideband",
        "super sqv",
        "sqv4",
        "blow off valve",
        "blow-off valve",
        "valcon",
        "vcam",
        "vcamshaft",
        "stem-seal",
        "stem seal",
        "cylinder liner",
        "ring gasket",
        "complete engine",
        "engine assembly",
        "long block",
        "short block",
        "carbon plug cover",
        "cover transistor",
        "racing pro oil",
        "racing oil",
        "super zero racing",
        "super na racing",
        "engine oil",
        "motor oil",
        "0w-20",
        "0w-30",
        "0w-40",
        "5w-30",
        "5w-40",
        "10w-40",
        "10w-50",
        "10w-60",
        "gear oil",
        "g-900",
        "dctf",
        "dct fluid",
        "dct cooler",
        "torque mount",
        "skid plate",
        "shift linkage",
        "wiring conversion",
        "conversion harness",
        "rear bracket",
        "accessport",
        "high flow filter",
        "stage 1",
        "stage 2",
        "stage 3",
        "power package",
        "flex fuel",
        "flex-fuel",
        "openflash",
        "ecu flashing",
        "pdk flashing",
        "dsg flashing",
        "surge tank",
        "fuel cell",
        "in-tank",
        "phantom series",
        "fpr",
        "fuel pressure regulator",
        "pulley kit",
        "alternator pulley",
        "underdrive",
        "aeromotive",
        "microglass",
        "10-micron",
        "100-micron",
        "stainless mesh",
        "filter element",
        "filter housing",
        "loctite",
        "rtv silicone",
        "battery box",
        "breather filter",
    ],
    "wheels": [
        "wheel",
        "wheels",
        "rim",
        "rims",
        "tire",
        "tires",
        "tyre",
        "tyres",
        "lug",
        "lug nut",
        "lug bolt",
        "lug bolts",
        "stud conversion",
        "stud conversion kit",
        "wheel stud",
        "wheel studs",
        "extended stud",
        "extended studs",
        "wheel hub",
        "wheel hubs",
        "hubcentric",
        "hub centric",
        "wheel spacer",
        "wheel spacers",
        "center cap",
        "centercap",
        "gram lights",
        "volk",
        "te37",
        "enkei",
        "bbs",
        "rotiform",
        "ce28",
        "ce28n",
        "57cr",
        "57xtreme",
        "club racer",
        "color clear",
        "black machine",
        "silver machine",
        "bronze color",
        "machine finish",
        "tuner nut",
        "lock nut",
        "wheel lock",
        "lock & nut",
        "double lock nut",
        "bull lock",
        "wide tread spacer",
        "duralumin lock",
        "beadlock",
    ],
    "body": [
        "body kit",
        "bodykit",
        "spoiler",
        "wing",
        "splitter",
        "lip",
        "diffuser",
        "bumper",
        "fender",
        "hood",
        "aero",
        "aerodynamic",
        "side skirt",
        "widebody",
        "wide body",
        "grille",
        "grill",
        "carbon fiber",
        "cf ",
        "door garnish",
        "garnish",
        "decal",
        "decals",
        "tow hook",
        "license plate",
        "relocate bracket",
        "roof spoiler",
        "dive plane",
        "canard",
        "canards",
        "wind buffeting",
        "buffeting",
        "badge",
        "rock guard",
        "rock guards",
        "rocker",
        "rocker extension",
        "side rocker",
        "mud flap",
        "mud flaps",
        "carbon mirror",
        "mirror cover",
        "mirror shroud",
        "door mirror",
        "door pull",
        "door pocket",
        "door lock",
        "windshield wiper",
        "wiper blade",
        "wiper blades",
        "wiper arm",
        "sun visor",
        "visor mirror",
        "fuse box cover",
        "trunk handle",
    ],
    "interior": [
        "seat",
        "seats",
        "steering wheel",
        "steering wheels",
        "shift knob",
        "shifter",
        "shift paddle",
        "shift paddles",
        "paddle shift",
        "harness",
        "harness bar",
        "roll bar",
        "rollbar",
        "cage",
        "floor mat",
        "pedal",
        "gauge",
        "cluster",
        "interior",
        "trim",
        "alcantara",
        "bucket seat",
        "switch panel",
        "door switch panel",
        "storage compartment",
        "compartment cover",
        "console lid",
        "armrest",
        "door sill",
        "sill cover",
        "center console",
        "speaker cover",
        "helmet",
        "hans device",
        "racing suit",
        "driving shoe",
        "driving shoes",
        "race glove",
        "race gloves",
        "nomex",
        "fire extinguisher",
        "window net",
        "rain suit",
        "kart suit",
        "karting suit",
        "karting shoe",
        "arai",
        "sparco",
        "alpinestars",
        "stand21",
        "sabelt",
        "schroth",
        "bell helmet",
        "brey krause",
        "safecraft",
        "floor mats",
        "floormat",
        "floorliner",
        "weathertech",
        "carpet floormat",
        "rubber mats",
        "cargo liner",
        "trunk liner",
        "tear-off",
        "tear off",
        "tearoff",
        "lifeline",
        "head and neck restraint",
        "frontal head restraint",
    ],
    "brakes": [
        "brake",
        "brakes",
        "pad",
        "pads",
        "rotor",
        "rotors",
        "caliper",
        "calipers",
        "brake line",
        "brakeline",
        "brake fluid",
        "bbk",
        "big brake",
        "slotted",
        "drilled",
        "stainless line",
        "brake kit",
    ],
    "lighting": [
        "headlight",
        "headlights",
        "headlamp",
        "taillight",
        "taillights",
        "tail light",
        "tail lamp",
        "reverse light",
        "fog light",
        "fog lights",
        "fog lamp",
        "drl",
        "daytime running",
        "led",
        "hid",
        "light bar",
        "lightbar",
        "turn signal",
        "marker light",
        "lighting",
        "lamp",
        "bulb",
        "halo",
        "angel eye",
        "grille light",
        "reflector",
        "reflectors",
        "light cover",
        "light covers",
        "horn kit",
        "horn bracket",
    ],
    "drivetrain": [
        "differential",
        "diff",
        "diffs",
        "driveshaft",
        "drive shaft",
        "axle",
        "axles",
        "clutch",
        "flywheel",
        "transmission",
        "trans",
        "shaft",
        "cv joint",
        "driveline",
        "prop shaft",
        "half shaft",
        "lsd",
        "locker",
        "short shift",
        "short shift kit",
        "shift kit",
        "throw out bearing",
        "throw-out bearing",
        "release bearing",
        "clutch disc",
        "friction disc",
        "friction kit",
        "mcleod",
        "fidanza",
        "exedy",
        "pin drive",
    ],
    "accessories": [
        "t-shirt",
        "hat",
        "cap",
        "keychain",
        "keyring",
        "lanyard",
        "decal",
        "sticker",
        "emblem",
        "badge",
        "license plate frame",
        "license plate relocator",
        "floor mat",
        "mud flap",
        "wax",
        "polish",
        "cleaner",
        "microfiber",
        "jacket",
        "tee shirt",
        "shirt",
        "hoodie",
        "sweatshirt",
        "polo",
        "hoody",
        "beanie",
        "key holder",
        "key ring",
        "wallet",
        "umbrella",
        "duffle bag",
        "tote bag",
        "drying towel",
        "microfiber towel",
        "hand towel",
        "patch",
        "tote",
        "backpack",
        "scale model",
        "diecast",
        "die-cast",
        "1/18",
        "1/24",
        "1/43",
        "1/64",
        "workshop gloves",
        "neck gaiter",
        "apron",
        "mechanic apron",
        "raincoat",
        "kids sweater",
        "sweater",
        "logo tee",
        "ballcap",
        "porsche key",
        "key chain",
        "key blank",
        "porsche bug remover",
        "snapback",
        "car cover",
        "outdoor car cover",
        "premium car cover",
        "shipping insurance",
        "pollen filter",
        "cabin filter",
        "nano cabin filter",
        "scheduled maintenance",
        "maintenance service",
        "core charge",
        "core return",
    ],
}

MIN_SCORE = 1

NAME_WEIGHT = 2

STEERING_WHEEL_PHRASES = (
    "steering wheel",
    "steering wheels",
    "wheel cleaner",
    "wheel polish",
    "wheel wax",
)
WHEELS_AMBIGUOUS_KEYWORDS = frozenset({"wheel", "wheels"})

VALVE_SPRING_PHRASES = ("valve spring", "valve springs")
SUSPENSION_AMBIGUOUS_KEYWORDS = frozenset({"spring", "springs"})

LICENSE_PLATE_ACCESSORY_PHRASES = ("license plate frame", "license plate relocator")
BODY_AMBIGUOUS_LICENSE_KEYWORDS = frozenset({"license plate"})


def _score_text(text: str, keywords: list[str]) -> int:
    """Count how many of `keywords` appear in `text` on word boundaries.

    Each keyword scores at most once, so a repeated keyword in the category list
    does not double-count.
    """
    if not text or not keywords:
        return 0
    lower = text.lower()
    count = 0
    for kw in keywords:
        if re.search(r"\b" + re.escape(kw) + r"\b", lower):
            count += 1
    return count


def _score_text_wheels_aware(text: str, keywords: list[str], context: str) -> int:
    """
    Score for wheels category: exclude 'wheel'/'wheels' when context (e.g. name+description)
    clearly refers to steering wheel (e.g. "steering wheels shift paddles") so those go to interior.
    """
    if not text and not context:
        return _score_text(text, keywords)
    lower_context = (context or "").lower()
    if any(phrase in lower_context for phrase in STEERING_WHEEL_PHRASES):
        keywords = [kw for kw in keywords if kw not in WHEELS_AMBIGUOUS_KEYWORDS]
    return _score_text(text, keywords)


def _score_text_suspension_aware(text: str, keywords: list[str], context: str) -> int:
    """
    Score for suspension category: exclude plain ``spring``/``springs`` when context
    contains ``valve spring(s)`` (those are valve-train → engine, not suspension).
    """
    if not text and not context:
        return _score_text(text, keywords)
    lower_context = (context or "").lower()
    if any(phrase in lower_context for phrase in VALVE_SPRING_PHRASES):
        keywords = [kw for kw in keywords if kw not in SUSPENSION_AMBIGUOUS_KEYWORDS]
    return _score_text(text, keywords)


def _score_text_body_aware(text: str, keywords: list[str], context: str) -> int:
    """
    Score for body category: exclude plain ``license plate`` when context contains a
    more-specific accessories phrase (``license plate frame``/``license plate relocator``).
    """
    if not text and not context:
        return _score_text(text, keywords)
    lower_context = (context or "").lower()
    if any(phrase in lower_context for phrase in LICENSE_PLATE_ACCESSORY_PHRASES):
        keywords = [kw for kw in keywords if kw not in BODY_AMBIGUOUS_LICENSE_KEYWORDS]
    return _score_text(text, keywords)


def infer_category(
    name: Optional[str],
    description: Optional[str],
) -> Optional[str]:
    """Pick the best-scoring category for a part's name and description.

    Returns "other" when the best score is below `MIN_SCORE`, and `None` only when
    both name and description are empty, so the caller can apply its own default.
    """
    name = (name or "").strip()
    description = (description or "").strip()
    if not name and not description:
        return None

    best_name: Optional[str] = None
    best_score = -1
    combined = f"{name} {description}"

    for category, keywords in CATEGORY_KEYWORDS.items():
        if category == "wheels":
            name_score = _score_text_wheels_aware(name, keywords, combined) * NAME_WEIGHT
            desc_score = _score_text_wheels_aware(description, keywords, combined)
        elif category == "suspension":
            name_score = _score_text_suspension_aware(name, keywords, combined) * NAME_WEIGHT
            desc_score = _score_text_suspension_aware(description, keywords, combined)
        elif category == "body":
            name_score = _score_text_body_aware(name, keywords, combined) * NAME_WEIGHT
            desc_score = _score_text_body_aware(description, keywords, combined)
        else:
            name_score = _score_text(name, keywords) * NAME_WEIGHT
            desc_score = _score_text(description, keywords)
        total = name_score + desc_score
        if total > best_score:
            best_score = total
            best_name = category

    if best_name is None or best_score < MIN_SCORE:
        return "other"
    return best_name
