"""DATA-05 regression: FK columns carry ORM-declared indexes.

Asserts the state produced by plan 04-01's FK audit + autogenerated migration.
Introspection-only; no DB required (uses SQLAlchemy Table metadata).

See .planning/phases/04-db-parts-hardening/04-CONTEXT.md D-14 and D-15 for the
audit rules (composite-index left-prefix rule).
"""

from __future__ import annotations

from app.api.models.report import Report
from app.api.models.vote import Vote


def _column_is_indexed(table, column_name: str) -> bool:
    """True if column has index=True at mapped_column level OR is the leading
    column of an Index in __table_args__ (Postgres left-prefix rule)."""
    col = table.c[column_name]
    if col.index:
        return True
    for idx in table.indexes:
        cols = list(idx.columns)
        if cols and cols[0].name == column_name:
            return True
    return False


EXPECTED_INDEXED_FKS = [
    (Report, "reviewed_by"),
]


def test_expected_fk_indexes_present() -> None:
    """Every FK column targeted by D-15 has an index (column-level or composite leading)."""
    missing: list[str] = []
    for model, col in EXPECTED_INDEXED_FKS:
        if not _column_is_indexed(model.__table__, col):
            missing.append(f"{model.__tablename__}.{col}")
    assert not missing, f"FK columns missing index: {missing}"


def test_left_prefix_skip_honored() -> None:
    """Polymorphic user_id FKs must NOT carry column-level index=True.

    Vote.user_id is the leading column of ix_votes_user_entity_type and
    Report.user_id is the leading column of ix_reports_user_entity_type.
    Adding index=True to the mapped_column would duplicate the composite
    per D-14.
    """
    assert Vote.__table__.c["user_id"].index in (False, None), (
        "Vote.user_id should not carry column-level index=True; " "ix_votes_user_entity_type already left-prefixes it."
    )
    assert Report.__table__.c["user_id"].index in (False, None), (
        "Report.user_id should not carry column-level index=True; "
        "ix_reports_user_entity_type already left-prefixes it."
    )
