"""migration flatten

Revision ID: 04e42912c65c
Revises: b6665d92309f
Create Date: 2026-01-18 21:16:14.743412

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "04e42912c65c"
down_revision: Union[str, None] = "b6665d92309f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cars",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("make", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("generation_name", sa.String(), nullable=False),
        sa.Column("start_year", sa.Integer(), nullable=False),
        sa.Column("end_year", sa.Integer(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cars_id"), "cars", ["id"], unique=False)
    op.create_index(op.f("ix_cars_make"), "cars", ["make"], unique=False)
    op.create_index(op.f("ix_cars_model"), "cars", ["model"], unique=False)
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_categories_id"), "categories", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("subscription_tier", sa.String(), nullable=False),
        sa.Column("subscription_expires_at", sa.DateTime(), nullable=True),
        sa.Column("subscription_status", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "build_lists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column("car_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["car_id"],
            ["cars.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_build_lists_description"), "build_lists", ["description"], unique=False)
    op.create_index(op.f("ix_build_lists_id"), "build_lists", ["id"], unique=False)
    op.create_index(op.f("ix_build_lists_name"), "build_lists", ["name"], unique=False)
    op.create_table(
        "global_parts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("car_id", sa.Integer(), nullable=True),
        sa.Column("brand", sa.String(), nullable=True),
        sa.Column("part_number", sa.String(), nullable=True),
        sa.Column("specifications", sa.JSON(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("edit_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["car_id"],
            ["cars.id"],
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_global_parts_car_id"), "global_parts", ["car_id"], unique=False)
    op.create_index(op.f("ix_global_parts_id"), "global_parts", ["id"], unique=False)
    op.create_index(op.f("ix_global_parts_name"), "global_parts", ["name"], unique=False)
    op.create_table(
        "reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("admin_notes", sa.String(), nullable=True),
        sa.Column("reviewed_by", sa.Integer(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_reports_entity", "reports", ["entity_type", "entity_id"], unique=False)
    op.create_index(op.f("ix_reports_id"), "reports", ["id"], unique=False)
    op.create_index("ix_reports_status", "reports", ["status"], unique=False)
    op.create_index("ix_reports_user_entity_type", "reports", ["user_id", "entity_type"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("tier", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_subscriptions_id"), "subscriptions", ["id"], unique=False)
    op.create_table(
        "votes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("vote_type", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "entity_type", "entity_id", name="unique_user_entity_vote"),
    )
    op.create_index("ix_votes_entity", "votes", ["entity_type", "entity_id"], unique=False)
    op.create_index(op.f("ix_votes_id"), "votes", ["id"], unique=False)
    op.create_index("ix_votes_user_entity_type", "votes", ["user_id", "entity_type"], unique=False)
    op.create_table(
        "build_list_parts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("build_list_id", sa.Integer(), nullable=False),
        sa.Column("global_part_id", sa.Integer(), nullable=False),
        sa.Column("added_by", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("purchased", sa.Boolean(), nullable=False),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["added_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["build_list_id"],
            ["build_lists.id"],
        ),
        sa.ForeignKeyConstraint(
            ["global_part_id"],
            ["global_parts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_build_list_parts_id"), "build_list_parts", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_build_list_parts_id"), table_name="build_list_parts")
    # SAFE: downgrade reversal of already-applied migration — see SAFE-04
    op.drop_table("build_list_parts")
    op.drop_index("ix_votes_user_entity_type", table_name="votes")
    op.drop_index(op.f("ix_votes_id"), table_name="votes")
    op.drop_index("ix_votes_entity", table_name="votes")
    # SAFE: downgrade reversal of already-applied migration — see SAFE-04
    op.drop_table("votes")
    op.drop_index(op.f("ix_subscriptions_id"), table_name="subscriptions")
    # SAFE: downgrade reversal of already-applied migration — see SAFE-04
    op.drop_table("subscriptions")
    op.drop_index("ix_reports_user_entity_type", table_name="reports")
    op.drop_index("ix_reports_status", table_name="reports")
    op.drop_index(op.f("ix_reports_id"), table_name="reports")
    op.drop_index("ix_reports_entity", table_name="reports")
    # SAFE: downgrade reversal of already-applied migration — see SAFE-04
    op.drop_table("reports")
    op.drop_index(op.f("ix_global_parts_name"), table_name="global_parts")
    op.drop_index(op.f("ix_global_parts_id"), table_name="global_parts")
    op.drop_index(op.f("ix_global_parts_car_id"), table_name="global_parts")
    # SAFE: downgrade reversal of already-applied migration — see SAFE-04
    op.drop_table("global_parts")
    op.drop_index(op.f("ix_build_lists_name"), table_name="build_lists")
    op.drop_index(op.f("ix_build_lists_id"), table_name="build_lists")
    op.drop_index(op.f("ix_build_lists_description"), table_name="build_lists")
    # SAFE: downgrade reversal of already-applied migration — see SAFE-04
    op.drop_table("build_lists")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    # SAFE: downgrade reversal of already-applied migration — see SAFE-04
    op.drop_table("users")
    op.drop_index(op.f("ix_categories_id"), table_name="categories")
    # SAFE: downgrade reversal of already-applied migration — see SAFE-04
    op.drop_table("categories")
    op.drop_index(op.f("ix_cars_model"), table_name="cars")
    op.drop_index(op.f("ix_cars_make"), table_name="cars")
    op.drop_index(op.f("ix_cars_id"), table_name="cars")
    # SAFE: downgrade reversal of already-applied migration — see SAFE-04
    op.drop_table("cars")
    # ### end Alembic commands ###
