"""add adapter_schedules table

Revision ID: 052f603511ed
Revises: e3f4b1c08a91
Create Date: 2026-04-18 12:56:02.102598

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '052f603511ed'
down_revision: Union[str, None] = 'e3f4b1c08a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adapter_schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('adapter_name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule_expression', sa.String(), nullable=False),
    sa.Column('delay_sec', sa.Float(), nullable=False),
    sa.Column('per_run_limit', sa.Integer(), nullable=True),
    sa.Column('skip_known_urls', sa.Boolean(), nullable=False),
    sa.Column('default_category_id', sa.Uuid(), nullable=False),
    sa.Column('last_reconciled_at', sa.DateTime(), nullable=True),
    sa.Column('last_reconcile_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['default_category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adapter_schedules_adapter_name'), 'adapter_schedules', ['adapter_name'], unique=True)
    op.create_index(op.f('ix_adapter_schedules_id'), 'adapter_schedules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adapter_schedules_id'), table_name='adapter_schedules')
    op.drop_index(op.f('ix_adapter_schedules_adapter_name'), table_name='adapter_schedules')
    op.drop_table('adapter_schedules')
    # ### end Alembic commands ###
