"""add canonical_part_id to parts

Revision ID: 097024200e60
Revises: c2e5af5ef24f
Create Date: 2026-04-20 20:55:32.951336

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "097024200e60"
down_revision: Union[str, None] = "c2e5af5ef24f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("parts", sa.Column("canonical_part_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_parts_canonical_part_id"), "parts", ["canonical_part_id"], unique=False)
    op.create_foreign_key(None, "parts", "parts", ["canonical_part_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SAFE: legacy drop_constraint(None) superseded by forward-only repair in aa583927d86a — see SAFE-08
    op.drop_constraint(None, "parts", type_="foreignkey")
    op.drop_index(op.f("ix_parts_canonical_part_id"), table_name="parts")
    op.drop_column("parts", "canonical_part_id")
    # ### end Alembic commands ###
