"""add_build_list_phases

Revision ID: 172d1c205fb3
Revises: 98b114b6b62f
Create Date: 2026-03-13 21:57:55.217389

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "172d1c205fb3"
down_revision: Union[str, None] = "98b114b6b62f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "build_list_phases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("build_list_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["build_list_id"], ["build_lists.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_build_list_phases_id"), "build_list_phases", ["id"], unique=False)
    op.add_column("build_list_parts", sa.Column("build_list_phase_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "build_list_parts", "build_list_phases", ["build_list_phase_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SAFE: legacy drop_constraint(None) superseded by forward-only repair in aa583927d86a — see SAFE-08
    op.drop_constraint(None, "build_list_parts", type_="foreignkey")
    op.drop_column("build_list_parts", "build_list_phase_id")
    op.drop_index(op.f("ix_build_list_phases_id"), table_name="build_list_phases")
    op.drop_table("build_list_phases")
    # ### end Alembic commands ###
