"""make_car_id_optional_in_build_lists

Revision ID: 1b17f9e4db9b
Revises: b329466dffc6
Create Date: 2025-08-24 18:59:12.120047

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1b17f9e4db9b"
down_revision: Union[str, None] = "b329466dffc6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("build_lists", "car_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("build_lists", "car_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
