"""add new price history related entities

Revision ID: 1e4d5e144c47
Revises: 6eae6b1393c5
Create Date: 2026-01-29 18:50:53.572848

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e4d5e144c47"
down_revision: Union[str, None] = "6eae6b1393c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "retailers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("domain", sa.String(), nullable=True),
        sa.Column("base_url", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_retailers_domain"), "retailers", ["domain"], unique=False)
    op.create_index(op.f("ix_retailers_id"), "retailers", ["id"], unique=False)
    op.create_index(op.f("ix_retailers_name"), "retailers", ["name"], unique=False)
    op.create_table(
        "part_listings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("global_part_id", sa.Integer(), nullable=False),
        sa.Column("retailer_id", sa.Integer(), nullable=False),
        sa.Column("product_url", sa.String(), nullable=True),
        sa.Column("last_known_price_cents", sa.Integer(), nullable=True),
        sa.Column("last_price_updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["global_part_id"],
            ["global_parts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["retailer_id"],
            ["retailers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("global_part_id", "retailer_id", name="uq_part_listing_global_part_retailer"),
    )
    op.create_index(op.f("ix_part_listings_global_part_id"), "part_listings", ["global_part_id"], unique=False)
    op.create_index(op.f("ix_part_listings_id"), "part_listings", ["id"], unique=False)
    op.create_index(op.f("ix_part_listings_retailer_id"), "part_listings", ["retailer_id"], unique=False)
    op.create_table(
        "part_price_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("part_listing_id", sa.Integer(), nullable=False),
        sa.Column("price_cents", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["part_listing_id"],
            ["part_listings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_part_price_history_id"), "part_price_history", ["id"], unique=False)
    op.create_index(op.f("ix_part_price_history_observed_at"), "part_price_history", ["observed_at"], unique=False)
    op.create_index(
        op.f("ix_part_price_history_part_listing_id"), "part_price_history", ["part_listing_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_part_price_history_part_listing_id"), table_name="part_price_history")
    op.drop_index(op.f("ix_part_price_history_observed_at"), table_name="part_price_history")
    op.drop_index(op.f("ix_part_price_history_id"), table_name="part_price_history")
    op.drop_table("part_price_history")
    op.drop_index(op.f("ix_part_listings_retailer_id"), table_name="part_listings")
    op.drop_index(op.f("ix_part_listings_id"), table_name="part_listings")
    op.drop_index(op.f("ix_part_listings_global_part_id"), table_name="part_listings")
    op.drop_table("part_listings")
    op.drop_index(op.f("ix_retailers_name"), table_name="retailers")
    op.drop_index(op.f("ix_retailers_id"), table_name="retailers")
    op.drop_index(op.f("ix_retailers_domain"), table_name="retailers")
    op.drop_table("retailers")
    # ### end Alembic commands ###
