"""add_superuser_fields_to_users

Revision ID: 29413bf5323b
Revises: 58158c9af082
Create Date: 2025-08-19 23:23:27.451803

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "29413bf5323b"
down_revision: Union[str, None] = "58158c9af082"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column("users", sa.Column("is_superuser", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("is_admin", sa.Boolean(), nullable=True))

    # Set default values for existing rows
    op.execute("UPDATE users SET is_superuser = false, is_admin = false")

    # Make columns not nullable
    op.alter_column("users", "is_superuser", nullable=False)
    op.alter_column("users", "is_admin", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_admin")
    op.drop_column("users", "is_superuser")
    # ### end Alembic commands ###
