"""many refactors

Revision ID: 2d389160410b
Revises: 6eae6b1393c5
Create Date: 2026-01-31 17:52:15.334316

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d389160410b"
down_revision: Union[str, None] = "6eae6b1393c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image_source_mappings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_url", sa.String(), nullable=False),
        sa.Column("file_key", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_url", name="uq_image_source_mapping_source_url"),
    )
    op.create_index(op.f("ix_image_source_mappings_id"), "image_source_mappings", ["id"], unique=False)
    op.create_index(op.f("ix_image_source_mappings_source_url"), "image_source_mappings", ["source_url"], unique=False)
    op.create_table(
        "retailers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("domain", sa.String(), nullable=True),
        sa.Column("base_url", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_retailers_domain"), "retailers", ["domain"], unique=False)
    op.create_index(op.f("ix_retailers_id"), "retailers", ["id"], unique=False)
    op.create_index(op.f("ix_retailers_name"), "retailers", ["name"], unique=False)
    op.create_table(
        "part_listings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("global_part_id", sa.Integer(), nullable=False),
        sa.Column("retailer_id", sa.Integer(), nullable=False),
        sa.Column("product_url", sa.String(), nullable=True),
        sa.Column("last_known_price_cents", sa.Integer(), nullable=True),
        sa.Column("last_price_updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["global_part_id"],
            ["global_parts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["retailer_id"],
            ["retailers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("global_part_id", "retailer_id", name="uq_part_listing_global_part_retailer"),
    )
    op.create_index(op.f("ix_part_listings_global_part_id"), "part_listings", ["global_part_id"], unique=False)
    op.create_index(op.f("ix_part_listings_id"), "part_listings", ["id"], unique=False)
    op.create_index(op.f("ix_part_listings_retailer_id"), "part_listings", ["retailer_id"], unique=False)
    op.create_table(
        "part_price_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("part_listing_id", sa.Integer(), nullable=False),
        sa.Column("price_cents", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["part_listing_id"],
            ["part_listings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_part_price_history_id"), "part_price_history", ["id"], unique=False)
    op.create_index(op.f("ix_part_price_history_observed_at"), "part_price_history", ["observed_at"], unique=False)
    op.create_index(
        op.f("ix_part_price_history_part_listing_id"), "part_price_history", ["part_listing_id"], unique=False
    )
    op.add_column("global_parts", sa.Column("image_urls", sa.JSON(), nullable=True))
    op.add_column("global_parts", sa.Column("gtin", sa.String(), nullable=True))
    op.create_index(op.f("ix_global_parts_gtin"), "global_parts", ["gtin"], unique=False)
    # SAFE: downgrade reversal of already-applied migration — see SAFE-04
    op.drop_column("global_parts", "product_url")
    # SAFE: downgrade reversal of already-applied migration — see SAFE-04
    op.drop_column("global_parts", "price")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("global_parts", sa.Column("price", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column("global_parts", sa.Column("product_url", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f("ix_global_parts_gtin"), table_name="global_parts")
    # SAFE: downgrade reversal of already-applied migration — see SAFE-04
    op.drop_column("global_parts", "gtin")
    # SAFE: downgrade reversal of already-applied migration — see SAFE-04
    op.drop_column("global_parts", "image_urls")
    op.drop_index(op.f("ix_part_price_history_part_listing_id"), table_name="part_price_history")
    op.drop_index(op.f("ix_part_price_history_observed_at"), table_name="part_price_history")
    op.drop_index(op.f("ix_part_price_history_id"), table_name="part_price_history")
    # SAFE: downgrade reversal of already-applied migration — see SAFE-04
    op.drop_table("part_price_history")
    op.drop_index(op.f("ix_part_listings_retailer_id"), table_name="part_listings")
    op.drop_index(op.f("ix_part_listings_id"), table_name="part_listings")
    op.drop_index(op.f("ix_part_listings_global_part_id"), table_name="part_listings")
    # SAFE: downgrade reversal of already-applied migration — see SAFE-04
    op.drop_table("part_listings")
    op.drop_index(op.f("ix_retailers_name"), table_name="retailers")
    op.drop_index(op.f("ix_retailers_id"), table_name="retailers")
    op.drop_index(op.f("ix_retailers_domain"), table_name="retailers")
    # SAFE: downgrade reversal of already-applied migration — see SAFE-04
    op.drop_table("retailers")
    op.drop_index(op.f("ix_image_source_mappings_source_url"), table_name="image_source_mappings")
    op.drop_index(op.f("ix_image_source_mappings_id"), table_name="image_source_mappings")
    # SAFE: downgrade reversal of already-applied migration — see SAFE-04
    op.drop_table("image_source_mappings")
    # ### end Alembic commands ###
