"""build logs

Revision ID: 2fcc857ad593
Revises: a7b5e43f2000
Create Date: 2026-01-19 20:03:30.521054

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2fcc857ad593"
down_revision: Union[str, None] = "a7b5e43f2000"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "build_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("build_list_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["build_list_id"],
            ["build_lists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("build_list_id", name="uq_build_logs_build_list_id"),
    )
    op.create_index(op.f("ix_build_logs_build_list_id"), "build_logs", ["build_list_id"], unique=True)
    op.create_index(op.f("ix_build_logs_id"), "build_logs", ["id"], unique=False)
    op.create_table(
        "build_log_posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("build_log_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["build_log_id"],
            ["build_logs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_build_log_posts_build_log_id"), "build_log_posts", ["build_log_id"], unique=False)
    op.create_index(op.f("ix_build_log_posts_id"), "build_log_posts", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_build_log_posts_id"), table_name="build_log_posts")
    op.drop_index(op.f("ix_build_log_posts_build_log_id"), table_name="build_log_posts")
    op.drop_table("build_log_posts")
    op.drop_index(op.f("ix_build_logs_id"), table_name="build_logs")
    op.drop_index(op.f("ix_build_logs_build_list_id"), table_name="build_logs")
    op.drop_table("build_logs")
    # ### end Alembic commands ###
