"""fix_index_names_after_table_renames

Revision ID: 345c036fdb7c
Revises: 8014088c17c0
Create Date: 2025-08-24 16:19:46.214331

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "345c036fdb7c"
down_revision: Union[str, None] = "8014088c17c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_part_reports_id"), table_name="global_part_reports")
    op.create_index(
        op.f("ix_global_part_reports_id"), "global_part_reports", ["id"], unique=False
    )
    op.drop_index(op.f("ix_part_votes_id"), table_name="global_part_votes")
    op.create_index(
        op.f("ix_global_part_votes_id"), "global_part_votes", ["id"], unique=False
    )
    op.drop_index(op.f("ix_parts_id"), table_name="global_parts")
    op.drop_index(op.f("ix_parts_name"), table_name="global_parts")
    op.create_index(op.f("ix_global_parts_id"), "global_parts", ["id"], unique=False)
    op.create_index(
        op.f("ix_global_parts_name"), "global_parts", ["name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_global_parts_name"), table_name="global_parts")
    op.drop_index(op.f("ix_global_parts_id"), table_name="global_parts")
    op.create_index(op.f("ix_parts_name"), "global_parts", ["name"], unique=False)
    op.create_index(op.f("ix_parts_id"), "global_parts", ["id"], unique=False)
    op.drop_index(op.f("ix_global_part_votes_id"), table_name="global_part_votes")
    op.create_index(op.f("ix_part_votes_id"), "global_part_votes", ["id"], unique=False)
    op.drop_index(op.f("ix_global_part_reports_id"), table_name="global_part_reports")
    op.create_index(
        op.f("ix_part_reports_id"), "global_part_reports", ["id"], unique=False
    )
    # ### end Alembic commands ###
