"""add_user_id_to_build_lists

Revision ID: 3bf85f85fc2a
Revises: 8eb02afa8829
Create Date: 2025-08-19 22:20:53.068463

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3bf85f85fc2a"
down_revision: Union[str, None] = "8eb02afa8829"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add user_id column as nullable first
    op.add_column("build_lists", sa.Column("user_id", sa.Integer(), nullable=True))

    # Set user_id based on car owner for existing build lists
    op.execute(
        """
        UPDATE build_lists 
        SET user_id = (
            SELECT cars.user_id 
            FROM cars 
            WHERE cars.id = build_lists.car_id
        )
    """
    )

    # Make user_id not nullable
    op.alter_column("build_lists", "user_id", nullable=False)

    # Add foreign key constraint
    op.create_foreign_key(
        "fk_build_lists_user_id", "build_lists", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_build_lists_user_id", "build_lists", type_="foreignkey")
    op.drop_column("build_lists", "user_id")
    # ### end Alembic commands ###
