"""made car end year nullable

Revision ID: 42233da3eb45
Revises: a72c61dfbb9c
Create Date: 2026-01-18 19:18:17.089110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42233da3eb45'
down_revision: Union[str, None] = 'a72c61dfbb9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cars', 'end_year',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cars', 'end_year',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
