"""auth expiry control and socials

Revision ID: 46ca3f447c85
Revises: 2d389160410b
Create Date: 2026-02-01 13:00:18.009966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46ca3f447c85'
down_revision: Union[str, None] = '2d389160410b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('session_expire_minutes', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('instagram_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('facebook_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reddit_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('youtube_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('tiktok_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tiktok_url')
    op.drop_column('users', 'youtube_url')
    op.drop_column('users', 'reddit_url')
    op.drop_column('users', 'facebook_url')
    op.drop_column('users', 'instagram_url')
    op.drop_column('users', 'session_expire_minutes')
    # ### end Alembic commands ###
