"""add_category_system

Revision ID: 4e70751f099f
Revises: 3bf85f85fc2a
Create Date: 2025-08-19 22:28:45.496841

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4e70751f099f"
down_revision: Union[str, None] = "3bf85f85fc2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_categories_id"), "categories", ["id"], unique=False)

    # Insert default categories
    op.execute(
        """
        INSERT INTO categories (name, display_name, description, sort_order, is_active, created_at, updated_at) VALUES
        ('exhaust', 'Exhaust Systems', 'Exhaust headers, cat-back systems, mufflers', 1, true, NOW(), NOW()),
        ('intake', 'Intake Systems', 'Cold air intakes, air filters, throttle bodies', 2, true, NOW(), NOW()),
        ('suspension', 'Suspension', 'Coilovers, shocks, springs, sway bars', 3, true, NOW(), NOW()),
        ('wheels', 'Wheels & Tires', 'Wheels, tires, wheel accessories', 4, true, NOW(), NOW()),
        ('brakes', 'Brake Systems', 'Brake pads, rotors, calipers, brake lines', 5, true, NOW(), NOW()),
        ('engine', 'Engine Performance', 'Turbochargers, superchargers, engine management', 6, true, NOW(), NOW()),
        ('exterior', 'Exterior', 'Body kits, spoilers, lighting, mirrors', 7, true, NOW(), NOW()),
        ('interior', 'Interior', 'Seats, steering wheels, shifters, gauges', 8, true, NOW(), NOW()),
        ('electrical', 'Electrical', 'Batteries, alternators, wiring, audio', 9, true, NOW(), NOW()),
        ('maintenance', 'Maintenance', 'Oil, filters, fluids, tools', 10, true, NOW(), NOW()),
        ('other', 'Other', 'Miscellaneous parts and accessories', 99, true, NOW(), NOW())
    """
    )

    # Add category_id column as nullable first
    op.add_column("parts", sa.Column("category_id", sa.Integer(), nullable=True))

    # Set default category for existing parts
    op.execute(
        """
        UPDATE parts 
        SET category_id = (
            SELECT id FROM categories WHERE name = 'other' LIMIT 1
        )
    """
    )

    # Make category_id not nullable
    op.alter_column("parts", "category_id", nullable=False)

    # Add foreign key constraint
    op.create_foreign_key(
        "fk_parts_category_id", "parts", "categories", ["category_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_parts_category_id", "parts", type_="foreignkey")
    op.drop_column("parts", "category_id")
    op.drop_index(op.f("ix_categories_id"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
