"""consolidate_image_url_to_image_urls

Revision ID: 5f5924feaa24
Revises: 274bde4f4654
Create Date: 2026-04-15 19:24:26.234892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f5924feaa24'
down_revision: Union[str, None] = '274bde4f4654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('background_jobs', 'params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('background_jobs', 'result_summary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)

    # --- global_parts: merge image_url into image_urls[0] before dropping ---
    # If image_url is set and not already in the gallery, prepend it as the primary image.
    op.execute("""
        UPDATE global_parts
        SET image_urls = CASE
            WHEN image_urls IS NULL THEN json_build_array(image_url)
            WHEN image_urls::jsonb @> to_jsonb(image_url) THEN image_urls
            ELSE (to_jsonb(ARRAY[image_url]) || image_urls::jsonb)::json
        END
        WHERE image_url IS NOT NULL
    """)
    op.drop_column('global_parts', 'image_url')

    # --- build_lists: add image_urls, backfill from image_url, drop image_url ---
    op.add_column('build_lists', sa.Column('image_urls', sa.JSON(), nullable=True))
    op.execute("""
        UPDATE build_lists SET image_urls = json_build_array(image_url) WHERE image_url IS NOT NULL
    """)
    op.drop_column('build_lists', 'image_url')

    # --- cars: add image_urls, backfill from image_url, drop image_url ---
    op.add_column('cars', sa.Column('image_urls', sa.JSON(), nullable=True))
    op.execute("""
        UPDATE cars SET image_urls = json_build_array(image_url) WHERE image_url IS NOT NULL
    """)
    op.drop_column('cars', 'image_url')

    # --- users: add image_urls, backfill from image_url, drop image_url ---
    op.add_column('users', sa.Column('image_urls', sa.JSON(), nullable=True))
    op.execute("""
        UPDATE users SET image_urls = json_build_array(image_url) WHERE image_url IS NOT NULL
    """)
    op.drop_column('users', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # --- users: restore image_url from image_urls[0] ---
    op.add_column('users', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.execute("""
        UPDATE users SET image_url = image_urls->>0 WHERE image_urls IS NOT NULL AND json_array_length(image_urls) > 0
    """)
    op.drop_column('users', 'image_urls')

    # --- global_parts: restore image_url from image_urls[0] ---
    op.add_column('global_parts', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.execute("""
        UPDATE global_parts SET image_url = image_urls->>0 WHERE image_urls IS NOT NULL AND json_array_length(image_urls) > 0
    """)

    # --- cars: restore image_url from image_urls[0] ---
    op.add_column('cars', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.execute("""
        UPDATE cars SET image_url = image_urls->>0 WHERE image_urls IS NOT NULL AND json_array_length(image_urls) > 0
    """)
    op.drop_column('cars', 'image_urls')

    # --- build_lists: restore image_url from image_urls[0] ---
    op.add_column('build_lists', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.execute("""
        UPDATE build_lists SET image_url = image_urls->>0 WHERE image_urls IS NOT NULL AND json_array_length(image_urls) > 0
    """)
    op.drop_column('build_lists', 'image_urls')

    op.alter_column('background_jobs', 'result_summary',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('background_jobs', 'params',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
