"""add_crawled_pages

Revision ID: 6e24c3c398d8
Revises: 172d1c205fb3
Create Date: 2026-04-11 20:37:25.282981

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e24c3c398d8"
down_revision: Union[str, None] = "172d1c205fb3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crawled_pages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("html_s3_key", sa.String(), nullable=True),
        sa.Column("html_local_path", sa.String(), nullable=True),
        sa.Column("crawled_at", sa.DateTime(), nullable=False),
        sa.Column("last_parsed_at", sa.DateTime(), nullable=True),
        sa.Column("parse_status", sa.String(), nullable=False),
        sa.Column("global_part_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["global_part_id"], ["global_parts.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url", name="uq_crawled_page_url"),
    )
    op.create_index(op.f("ix_crawled_pages_global_part_id"), "crawled_pages", ["global_part_id"], unique=False)
    op.create_index(op.f("ix_crawled_pages_id"), "crawled_pages", ["id"], unique=False)
    op.create_index(op.f("ix_crawled_pages_url"), "crawled_pages", ["url"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_crawled_pages_url"), table_name="crawled_pages")
    op.drop_index(op.f("ix_crawled_pages_id"), table_name="crawled_pages")
    op.drop_index(op.f("ix_crawled_pages_global_part_id"), table_name="crawled_pages")
    # SAFE: downgrade reversal of already-applied migration — see SAFE-04
    op.drop_table("crawled_pages")
    # ### end Alembic commands ###
