"""add brand model

Revision ID: 6eae6b1393c5
Revises: 7d821b0af913
Create Date: 2026-01-25 17:48:34.875338

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6eae6b1393c5"
down_revision: Union[str, None] = "7d821b0af913"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brands",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_brands_id"), "brands", ["id"], unique=False)
    op.create_index(op.f("ix_brands_name"), "brands", ["name"], unique=True)
    op.add_column("global_parts", sa.Column("brand_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_global_parts_brand_id"), "global_parts", ["brand_id"], unique=False)
    op.create_foreign_key(None, "global_parts", "brands", ["brand_id"], ["id"])
    op.drop_column("global_parts", "brand")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("global_parts", sa.Column("brand", sa.VARCHAR(), autoincrement=False, nullable=True))
    # SAFE: legacy drop_constraint(None) superseded by forward-only repair in aa583927d86a — see SAFE-08
    op.drop_constraint(None, "global_parts", type_="foreignkey")
    op.drop_index(op.f("ix_global_parts_brand_id"), table_name="global_parts")
    op.drop_column("global_parts", "brand_id")
    op.drop_index(op.f("ix_brands_name"), table_name="brands")
    op.drop_index(op.f("ix_brands_id"), table_name="brands")
    op.drop_table("brands")
    # ### end Alembic commands ###
