"""Add bug_reports table

Revision ID: 7d821b0af913
Revises: 4eef323a3826
Create Date: 2026-01-21 20:34:26.126485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d821b0af913'
down_revision: Union[str, None] = '4eef323a3826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('steps_to_reproduce', sa.String(), nullable=True),
    sa.Column('expected_behavior', sa.String(), nullable=True),
    sa.Column('actual_behavior', sa.String(), nullable=True),
    sa.Column('browser_info', sa.String(), nullable=True),
    sa.Column('device_info', sa.String(), nullable=True),
    sa.Column('screenshot_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('admin_notes', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bug_reports_created_at', 'bug_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_bug_reports_id'), 'bug_reports', ['id'], unique=False)
    op.create_index('ix_bug_reports_priority', 'bug_reports', ['priority'], unique=False)
    op.create_index('ix_bug_reports_status', 'bug_reports', ['status'], unique=False)
    op.create_index('ix_bug_reports_user_id', 'bug_reports', ['user_id'], unique=False)
    op.alter_column('build_log_posts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('build_log_posts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_bug_reports_user_id', table_name='bug_reports')
    op.drop_index('ix_bug_reports_status', table_name='bug_reports')
    op.drop_index('ix_bug_reports_priority', table_name='bug_reports')
    op.drop_index(op.f('ix_bug_reports_id'), table_name='bug_reports')
    op.drop_index('ix_bug_reports_created_at', table_name='bug_reports')
    op.drop_table('bug_reports')
    # ### end Alembic commands ###
