"""global_part_many_cars_and_is_universal

Revision ID: 82933b3bde38
Revises: 46ca3f447c85
Create Date: 2026-02-06 21:37:51.383527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82933b3bde38'
down_revision: Union[str, None] = '46ca3f447c85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_part_cars',
    sa.Column('global_part_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['global_part_id'], ['global_parts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('global_part_id', 'car_id')
    )
    op.add_column(
        'global_parts',
        sa.Column('is_universal', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.drop_index(op.f('ix_global_parts_car_id'), table_name='global_parts')
    op.drop_constraint(op.f('global_parts_car_id_fkey'), 'global_parts', type_='foreignkey')
    op.drop_column('global_parts', 'car_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_parts', sa.Column('car_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('global_parts_car_id_fkey'), 'global_parts', 'cars', ['car_id'], ['id'])
    op.create_index(op.f('ix_global_parts_car_id'), 'global_parts', ['car_id'], unique=False)
    op.drop_column('global_parts', 'is_universal')
    op.drop_table('global_part_cars')
    # ### end Alembic commands ###
