"""add_make_and_car_model_entities

Revision ID: 8ace51422235
Revises: 82933b3bde38
Create Date: 2026-02-07 12:36:11.480331

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import text

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ace51422235"
down_revision: Union[str, None] = "82933b3bde38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "makes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_makes_id"), "makes", ["id"], unique=False)
    op.create_index(op.f("ix_makes_name"), "makes", ["name"], unique=True)
    op.create_table(
        "car_models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("make_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["make_id"], ["makes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("make_id", "name", name="uq_car_models_make_id_name"),
    )
    op.create_index(op.f("ix_car_models_id"), "car_models", ["id"], unique=False)
    op.create_index(op.f("ix_car_models_make_id"), "car_models", ["make_id"], unique=False)
    op.create_index(op.f("ix_car_models_name"), "car_models", ["name"], unique=False)
    # Add column nullable first so existing rows don't violate NOT NULL
    op.add_column("cars", sa.Column("car_model_id", sa.Integer(), nullable=True))
    # Backfill: create make/car_model rows from existing cars.make/cars.model and set car_model_id
    conn = op.get_bind()
    rows = conn.execute(text("SELECT DISTINCT make, model FROM cars")).fetchall()
    for make_name, model_name in rows:
        # Ensure make exists
        make_row = conn.execute(text("SELECT id FROM makes WHERE name = :name"), {"name": make_name}).fetchone()
        if make_row is None:
            next_id = conn.execute(text("SELECT COALESCE(MAX(id), 0) + 1 FROM makes")).scalar()
            conn.execute(
                text(
                    "INSERT INTO makes (id, name, created_at, updated_at) VALUES (:id, :name, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"
                ),
                {"id": next_id, "name": make_name},
            )
            make_id = next_id
        else:
            make_id = make_row[0]
        # Ensure car_model exists
        cm_row = conn.execute(
            text("SELECT id FROM car_models WHERE make_id = :mid AND name = :name"),
            {"mid": make_id, "name": model_name},
        ).fetchone()
        if cm_row is None:
            next_cm_id = conn.execute(text("SELECT COALESCE(MAX(id), 0) + 1 FROM car_models")).scalar()
            conn.execute(
                text(
                    "INSERT INTO car_models (id, make_id, name, created_at, updated_at) VALUES (:id, :make_id, :name, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"
                ),
                {"id": next_cm_id, "make_id": make_id, "name": model_name},
            )
            car_model_id = next_cm_id
        else:
            car_model_id = cm_row[0]
        conn.execute(
            text("UPDATE cars SET car_model_id = :cmid WHERE make = :make AND model = :model"),
            {"cmid": car_model_id, "make": make_name, "model": model_name},
        )
    # Now set NOT NULL and add FK/indexes
    op.alter_column(
        "cars",
        "car_model_id",
        existing_type=sa.Integer(),
        nullable=False,
    )
    op.drop_index(op.f("ix_cars_make"), table_name="cars")
    op.drop_index(op.f("ix_cars_model"), table_name="cars")
    op.create_index(op.f("ix_cars_car_model_id"), "cars", ["car_model_id"], unique=False)
    op.create_foreign_key(op.f("cars_car_model_id_fkey"), "cars", "car_models", ["car_model_id"], ["id"], ondelete="CASCADE")
    op.drop_column("cars", "make")
    op.drop_column("cars", "model")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add make/model as nullable first so existing rows don't violate NOT NULL
    op.add_column("cars", sa.Column("model", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("cars", sa.Column("make", sa.VARCHAR(), autoincrement=False, nullable=True))
    # Backfill: populate make/model from car_models and makes before dropping car_model_id
    conn = op.get_bind()
    conn.execute(
        text("""
            UPDATE cars SET
                make = (SELECT m.name FROM car_models cm JOIN makes m ON cm.make_id = m.id WHERE cm.id = cars.car_model_id),
                model = (SELECT cm.name FROM car_models cm WHERE cm.id = cars.car_model_id)
        """)
    )
    # Now set NOT NULL
    op.alter_column("cars", "model", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("cars", "make", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_constraint(op.f("cars_car_model_id_fkey"), "cars", type_="foreignkey")
    op.drop_index(op.f("ix_cars_car_model_id"), table_name="cars")
    op.create_index(op.f("ix_cars_model"), "cars", ["model"], unique=False)
    op.create_index(op.f("ix_cars_make"), "cars", ["make"], unique=False)
    op.drop_column("cars", "car_model_id")
    op.drop_index(op.f("ix_car_models_name"), table_name="car_models")
    op.drop_index(op.f("ix_car_models_make_id"), table_name="car_models")
    op.drop_index(op.f("ix_car_models_id"), table_name="car_models")
    op.drop_table("car_models")
    op.drop_index(op.f("ix_makes_name"), table_name="makes")
    op.drop_index(op.f("ix_makes_id"), table_name="makes")
    op.drop_table("makes")
    # ### end Alembic commands ###
