"""add_image_source_mappings_table

Revision ID: 93f749a8da96
Revises: b515f4d091d7
Create Date: 2026-01-29 20:58:37.614921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93f749a8da96'
down_revision: Union[str, None] = 'b515f4d091d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_source_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('file_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url', name='uq_image_source_mapping_source_url')
    )
    op.create_index(op.f('ix_image_source_mappings_id'), 'image_source_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_image_source_mappings_source_url'), 'image_source_mappings', ['source_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_source_mappings_source_url'), table_name='image_source_mappings')
    op.drop_index(op.f('ix_image_source_mappings_id'), table_name='image_source_mappings')
    op.drop_table('image_source_mappings')
    # ### end Alembic commands ###
