"""replace adapter_schedules with crawler_schedules and adapter_configs

Revision ID: a568a3a2ba09
Revises: 052f603511ed
Create Date: 2026-04-18 13:26:27.843767

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a568a3a2ba09'
down_revision: Union[str, None] = '052f603511ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawler_schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule_expression', sa.String(), nullable=False),
    sa.Column('last_reconciled_at', sa.DateTime(), nullable=True),
    sa.Column('last_reconcile_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawler_schedules_id'), 'crawler_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_crawler_schedules_name'), 'crawler_schedules', ['name'], unique=True)
    op.create_table('crawler_adapter_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('adapter_name', sa.String(), nullable=False),
    sa.Column('delay_sec', sa.Float(), nullable=False),
    sa.Column('per_run_limit', sa.Integer(), nullable=True),
    sa.Column('skip_known_urls', sa.Boolean(), nullable=False),
    sa.Column('default_category_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['default_category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawler_adapter_configs_adapter_name'), 'crawler_adapter_configs', ['adapter_name'], unique=True)
    op.create_index(op.f('ix_crawler_adapter_configs_id'), 'crawler_adapter_configs', ['id'], unique=False)
    op.create_table('crawler_schedule_adapters',
    sa.Column('schedule_id', sa.Uuid(), nullable=False),
    sa.Column('adapter_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['crawler_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schedule_id', 'adapter_name')
    )
    op.drop_index(op.f('ix_adapter_schedules_adapter_name'), table_name='adapter_schedules')
    op.drop_index(op.f('ix_adapter_schedules_id'), table_name='adapter_schedules')
    op.drop_table('adapter_schedules')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adapter_schedules',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('adapter_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('schedule_expression', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('delay_sec', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('per_run_limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('skip_known_urls', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('default_category_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('last_reconciled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_reconcile_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['default_category_id'], ['categories.id'], name=op.f('adapter_schedules_default_category_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('adapter_schedules_pkey'))
    )
    op.create_index(op.f('ix_adapter_schedules_id'), 'adapter_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_adapter_schedules_adapter_name'), 'adapter_schedules', ['adapter_name'], unique=True)
    op.drop_table('crawler_schedule_adapters')
    op.drop_index(op.f('ix_crawler_adapter_configs_id'), table_name='crawler_adapter_configs')
    op.drop_index(op.f('ix_crawler_adapter_configs_adapter_name'), table_name='crawler_adapter_configs')
    op.drop_table('crawler_adapter_configs')
    op.drop_index(op.f('ix_crawler_schedules_name'), table_name='crawler_schedules')
    op.drop_index(op.f('ix_crawler_schedules_id'), table_name='crawler_schedules')
    op.drop_table('crawler_schedules')
    # ### end Alembic commands ###
