"""alembic dumb

Revision ID: a72c61dfbb9c
Revises: 6a5ca7e34fc8
Create Date: 2026-01-18 18:41:44.106430

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a72c61dfbb9c"
down_revision: Union[str, None] = "6a5ca7e34fc8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("global_parts", sa.Column("car_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_global_parts_car_id"), "global_parts", ["car_id"], unique=False)
    op.create_foreign_key(None, "global_parts", "cars", ["car_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "global_parts", type_="foreignkey")
    op.drop_index(op.f("ix_global_parts_car_id"), table_name="global_parts")
    op.drop_column("global_parts", "car_id")
    # ### end Alembic commands ###
