"""backfill build_logs for legacy build_lists

Revision ID: afdf25556c6c
Revises: 55291406b6a4
Create Date: 2026-04-22 20:43:14.656357

DATA-08 (Phase 4 D-23/D-24/D-26) — backfill build_logs for legacy build_lists.

Prior to the eager-create logic in build_list_service.py:82-88, new build_lists
did not auto-create a build_log row; the endpoint auto-created it lazily on
first read. This data migration closes the gap for legacy rows so deleting
the lazy branches in plan 04-02 task 2 (backend/app/api/endpoints/build_logs.py)
is safe.

Idempotent: WHERE NOT EXISTS guard guarantees re-runs insert at most once.
Forward-only: downgrade() is a deliberate no-op per D-26 (reversing would
destroy user posts captured against the backfilled rows).

Scaffold was autogenerated via `alembic revision --autogenerate`; autogenerate
also emitted naming_convention overlay output (constraint renames / FK re-adds)
that was discarded per D-13 / Pitfall 10 — those are forward-only deferrals
inherited from Phase 1 SAFE-09, not real schema work.
"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'afdf25556c6c'
down_revision: Union[str, None] = '55291406b6a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Backfill a build_log row for every build_list missing one. Idempotent.

    DATA-08 (Phase 4 D-24): prior to the eager-create logic in
    build_list_service.py:82-88, new build lists did not auto-create a build_log
    row; the endpoint auto-created it lazily on first read. This migration
    closes the gap for legacy rows so deleting the lazy branches in plan 04-02
    task 2 is safe.

    Uses Postgres-native gen_random_uuid() rather than a Python-side UUID
    callable (Pitfall 2: a Python callable fires once at statement-prepare
    time and every row would receive the same id, tripping
    uq_build_logs_build_list_id on row 2). Title format matches the
    eager-create precedent at build_list_service.py:85.
    """
    op.execute(sa.text("""
        INSERT INTO build_logs (id, build_list_id, title, created_at, updated_at)
        SELECT gen_random_uuid(), bl.id, 'Build Log: ' || bl.name, NOW(), NOW()
        FROM build_lists bl
        WHERE NOT EXISTS (
            SELECT 1 FROM build_logs bl2 WHERE bl2.build_list_id = bl.id
        )
    """))


def downgrade() -> None:
    # SAFE: forward-only data backfill; no reversal needed
    # Rationale (Phase 4 D-26): reversing would delete user posts captured
    # against the backfilled build_log rows. Git revert of the code change PR
    # is the functional rollback; data stays.
    pass
