"""add_quantity_field_to_build_list_parts

Revision ID: b329466dffc6
Revises: bb570c94e910
Create Date: 2025-08-24 18:53:34.357360

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b329466dffc6"
down_revision: Union[str, None] = "bb570c94e910"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column(
        "build_list_parts", sa.Column("quantity", sa.Integer(), nullable=True)
    )

    # Update existing records to have quantity = 1
    op.execute("UPDATE build_list_parts SET quantity = 1 WHERE quantity IS NULL")

    # Make column not nullable
    op.alter_column("build_list_parts", "quantity", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("build_list_parts", "quantity")
    # ### end Alembic commands ###
