"""add image url lists

Revision ID: b515f4d091d7
Revises: 67b76ed5f6cb
Create Date: 2026-01-29 20:33:41.979141

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b515f4d091d7"
down_revision: Union[str, None] = "67b76ed5f6cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("global_parts", sa.Column("image_urls", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("global_parts", "image_urls")
    # ### end Alembic commands ###
