"""Build out car build_list and part tables

Revision ID: c1c2b204718f
Revises: f61439fd5af3
Create Date: 2025-04-30 22:43:06.010911

"""

from typing import Sequence, Union

import sqlalchemy as sa  # noqa: F401
from sqlalchemy import inspect

from alembic import op  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = "c1c2b204718f"
down_revision: Union[str, None] = "f61439fd5af3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check which columns already exist to make migration idempotent
    bind = op.get_bind()
    inspector = inspect(bind)
    cars_columns = {col["name"] for col in inspector.get_columns("cars")}
    cars_indexes = {idx["name"] for idx in inspector.get_indexes("cars")}
    cars_foreign_keys = {fk["name"] for fk in inspector.get_foreign_keys("cars")}

    # ### commands auto generated by Alembic - please adjust! ###
    if "trim" not in cars_columns:
        op.add_column("cars", sa.Column("trim", sa.String(), nullable=True))

    if "user_id" not in cars_columns:
        # Add column as nullable first to handle existing rows
        op.add_column("cars", sa.Column("user_id", sa.Integer(), nullable=True))
        # Set a default user_id for existing rows (you may need to adjust this)
        # For now, we'll leave it nullable if there are existing rows
        # If you need it to be non-null, you'll need to provide a valid user_id
        # op.execute("UPDATE cars SET user_id = (SELECT id FROM users LIMIT 1) WHERE user_id IS NULL")
        # Then make it non-nullable:
        # op.alter_column("cars", "user_id", nullable=False)
        # For now, keeping it nullable to avoid data issues

    # Only alter columns if they need to be changed
    try:
        op.alter_column("cars", "make", existing_type=sa.VARCHAR(), nullable=False)
    except Exception:
        pass  # Column might already have correct nullability

    try:
        op.alter_column("cars", "model", existing_type=sa.VARCHAR(), nullable=False)
    except Exception:
        pass  # Column might already have correct nullability

    try:
        op.alter_column("cars", "year", existing_type=sa.INTEGER(), nullable=False)
    except Exception:
        pass  # Column might already have correct nullability

    if "ix_cars_trim" not in cars_indexes:
        op.create_index(op.f("ix_cars_trim"), "cars", ["trim"], unique=False)

    if "fk_cars_user_id" not in cars_foreign_keys:
        op.create_foreign_key("fk_cars_user_id", "cars", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_cars_user_id", "cars", type_="foreignkey")
    op.drop_index(op.f("ix_cars_trim"), table_name="cars")
    op.alter_column("cars", "year", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("cars", "model", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("cars", "make", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("cars", "user_id")
    op.drop_column("cars", "trim")
    # ### end Alembic commands ###
