"""add heartbeat and worker_instance_id to background_jobs

Revision ID: c2e5af5ef24f
Revises: bd2c48d79be9
Create Date: 2026-04-20 19:50:29.106072

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c2e5af5ef24f"
down_revision: Union[str, None] = "bd2c48d79be9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("background_jobs", sa.Column("last_heartbeat_at", sa.DateTime(), nullable=True))
    op.add_column("background_jobs", sa.Column("worker_instance_id", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_background_jobs_worker_instance_id"), "background_jobs", ["worker_instance_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_background_jobs_worker_instance_id"), table_name="background_jobs")
    # SAFE: downgrade reversal of already-applied migration — see SAFE-04
    op.drop_column("background_jobs", "worker_instance_id")
    # SAFE: downgrade reversal of already-applied migration — see SAFE-04
    op.drop_column("background_jobs", "last_heartbeat_at")
    # ### end Alembic commands ###
