"""add display_name to car_models and car_generations

Revision ID: c4e97fa3622b
Revises: a568a3a2ba09
Create Date: 2026-04-18 17:24:38.371807

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c4e97fa3622b'
down_revision: Union[str, None] = 'a568a3a2ba09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_generations', sa.Column('display_name', sa.String(), nullable=True))
    op.add_column('car_models', sa.Column('display_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_models', 'display_name')
    op.drop_column('car_generations', 'display_name')
    # ### end Alembic commands ###
