"""add accessories category

Revision ID: d1a4f7c2e8b3
Revises: f99b709f371a
Create Date: 2026-05-02 22:00:00.000000

Tier-2 data-quality audit Item #5: split apparel / branded swag /
cosmetic + detailing supplies out of the ``other`` catch-all into a
dedicated ``accessories`` category. Source of truth lives in
``app/core/part_categories_data.py``; ``init_part_categories`` syncs
display fields from source on startup, but the row itself must exist
before the keyword scorer can resolve the slug to a category id (the
crawler ingest path falls back to ``default_category_id`` when the
inferred slug has no active row), so we INSERT it here.

Also pushes ``other.sort_order`` from 10 -> 11 to keep accessories
sorted ahead of the catch-all.

This migration is hand-written rather than autogenerated because it
seeds data, not schema. Schema for ``categories`` is unchanged.
"""

import uuid
from typing import Sequence, Union

import sqlalchemy as sa
from uuid6 import uuid7

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1a4f7c2e8b3"
down_revision: Union[str, None] = "f99b709f371a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Insert accessories category row; bump other.sort_order to 11."""
    bind = op.get_bind()

    categories = sa.table(
        "categories",
        sa.column("id", sa.Uuid(as_uuid=True)),
        sa.column("name", sa.String()),
        sa.column("display_name", sa.String()),
        sa.column("description", sa.String()),
        sa.column("icon", sa.String()),
        sa.column("is_active", sa.Boolean()),
        sa.column("sort_order", sa.Integer()),
    )

    # Re-sort the existing ``other`` row first so we never have two rows
    # at sort_order=10 simultaneously (no DB constraint enforces this,
    # but the UI sorts on it and a tie would render in undefined order
    # mid-migration if reads raced the second statement).
    op.execute(
        sa.update(categories).where(categories.c.name == sa.literal("other")).values(sort_order=11)
    )

    # Insert accessories. Use uuid7 to match the model default; fall
    # back to a fresh uuid4 if the row already exists in a partially-
    # applied environment (idempotent by name).
    existing = bind.execute(
        sa.select(categories.c.id).where(categories.c.name == sa.literal("accessories"))
    ).first()
    if existing is None:
        op.execute(
            sa.insert(categories).values(
                id=uuid7(),
                name="accessories",
                display_name="Accessories & Apparel",
                description="Apparel, badges, decals, license plate frames, keychains, detailing supplies",
                icon="🎽",
                is_active=True,
                sort_order=10,
            )
        )


def downgrade() -> None:
    """Remove accessories category row; restore other.sort_order to 10."""
    categories = sa.table(
        "categories",
        sa.column("name", sa.String()),
        sa.column("sort_order", sa.Integer()),
    )

    # SAFE: downgrade reversal of already-applied migration — see SAFE-04
    op.execute(sa.delete(categories).where(categories.c.name == sa.literal("accessories")))
    # SAFE: downgrade reversal of already-applied migration — see SAFE-04
    op.execute(
        sa.update(categories).where(categories.c.name == sa.literal("other")).values(sort_order=10)
    )


# `uuid` import retained for type-checker; not used at module load.
_ = uuid
