"""Add hashed_password to users table

Revision ID: f61439fd5af3
Revises: acf219926b81
Create Date: 2025-04-29 22:06:46.749314

"""

from typing import Sequence, Union

import sqlalchemy as sa  # noqa: F401
from sqlalchemy import inspect

from alembic import op  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = "f61439fd5af3"
down_revision: Union[str, None] = "acf219926b81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check which columns already exist to make migration idempotent
    bind = op.get_bind()
    inspector = inspect(bind)
    users_columns = {col["name"] for col in inspector.get_columns("users")}

    # ### commands auto generated by Alembic - please adjust! ###
    if "hashed_password" not in users_columns:
        op.add_column("users", sa.Column("hashed_password", sa.String(), nullable=False))

    # Only alter columns if they exist and need to be changed
    # Note: These alter operations might fail if columns already have the correct type/nullability
    # but we'll let them fail gracefully if needed
    try:
        op.alter_column("users", "username", existing_type=sa.VARCHAR(), nullable=False)
    except Exception:
        pass  # Column might already have correct nullability

    try:
        op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=False)
    except Exception:
        pass  # Column might already have correct nullability

    try:
        op.alter_column("users", "disabled", existing_type=sa.BOOLEAN(), nullable=False)
    except Exception:
        pass  # Column might already have correct nullability
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "disabled", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "username", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
