"""
Buschur Racing (``buschurracing.com`` → ``buschursllc.com/br-cart/``)
crawler adapter — Tier 0 (plain HTTP).

Buschur Racing is a long-running Evo / DSM specialist (1G/2G DSM, Evo 7/8/9/X,
a little 22+ Ford Maverick and Ralliart). Their catalog mixes **house-brand
hardware** (``Buschur's 1G DSM Turbo Back Exhaust``, ``Buschur's 90-94 AWD
DSM 3" Downpipe Back``) with **third-party resale** (JE forged pistons,
Wiseco HD pistons, Tial wastegates, etc.), so we follow the multi-brand
pass-through pattern from ``ind.py`` / ``corksport.py`` /
``modernmusclextreme.py`` — NOT the single-brand coerce pattern.

Hosts
-----
- ``buschurracing.com`` — marketing domain; 302s to the real storefront at
  ``http://buschursllc.com/br-cart/`` (then 301 to https). The TLS cert on
  ``buschurracing.com`` does not cover the SAN — Apache serves the default
  ``buschursllc.com`` cert — which trips ``curl`` without ``-k`` but
  ``requests`` follows redirects without issue since it lands on the valid
  cert for the final host.
- ``buschuracing.com`` — a typo-catcher single-letter domain; returns a
  near-empty 80-byte placeholder page, NOT the store. We list it in the
  host map so archive rescrape can recognize the URL, but all discovery
  and default start URLs point at ``buschursllc.com/br-cart/``.
- ``buschursllc.com/br-cart/`` — the actual storefront path. Everything
  lives under the ``/br-cart/`` prefix (the root ``/`` is a near-empty
  static page). The site is served by Apache 2.2.11 + PHP 7.4 — classic
  legacy-box shape, but no Cloudflare or other active bot challenge, and
  plain ``requests`` with a browser-ish UA returns HTTP 200 for robots,
  categories, and product pages. Tier 0 is correct.

Platform: **PrestaShop 1.6 / 1.7-era** (theme ``theme1005``). Telltales: the
``<meta name="generator" content="PrestaShop" />`` tag, the boilerplate
``# robots.txt automaticaly generated by PrestaShop e-commerce open-source
solution`` header, the ``/br-cart/<category-slug>/<id>-<slug>.html`` URL
shape, the ``#product_reference`` + ``#our_price_display`` +
``#short_description_content`` DOM ids, and the ``itemprop="sku"`` /
``itemprop="name"`` / ``itemprop="price"`` microdata with a
``<meta property="product:price:amount">`` OG extension.

Structured data shape
---------------------
**No JSON-LD.** The page emits schema.org data as **microdata** inside the
``#product_reference`` / ``#our_price_display`` / content blocks plus the
standard ``og:*`` + ``product:price:*`` OpenGraph meta. Concretely:

- ``<h1>`` / ``<meta property="og:title">`` — product name (site-suffixed
  ``" - Buschurs LLC"`` in og:title, so we prefer ``<h1>``).
- ``<span itemprop="sku">…</span>`` inside ``#product_reference``. **Often
  blank** — house-brand items and many third-party resales have no SKU at
  all on this store. When present, values look like ``10170-JE`` (JE
  pistons) or ``10171-WIS`` (Wiseco) — a Buschur internal code with the
  manufacturer as a short suffix.
- ``<meta property="product:price:amount" content="680">`` +
  ``<meta property="product:price:currency" content="USD">`` — parsed via
  the shared ``extract_dom_price`` helper (which reads
  ``product:price:amount`` before falling back to body regex).
- ``<div class="rte">…</div>`` inside the product tab — the editorial
  description. Often a single sentence on this store, which we keep when
  present.
- ``#image-block img[src]`` — hero image at ``tm_large_default`` size.
  Thumbnail strip at ``#thumbs_list_frame img[src]`` (``tm_cart_default``
  size). We keep the hero; thumbnails are the same photos at smaller
  resolution so we don't dedupe the gallery further — there simply is no
  multi-image gallery on most products.

**Brand is never present in the microdata** — there is no
``itemprop="brand"`` / ``itemprop="manufacturer"`` anywhere on the product
page, and the ``<meta property="product:brand">`` tag is absent. So brand
resolution is entirely title-heuristic + SKU-suffix hint + a small
house-brand detector.

Variant rule (per VARIANTS.md)
------------------------------
PrestaShop supports combinations via ``<select name="group_*">`` /
``#idCombination`` pickers, but Buschur's catalog **does not use them** on
the pages we sampled — the ``#idCombination`` block renders empty and there
is no variant JSON blob. Variant-like differences (bore oversizes for JE
pistons, pipe diameters for downpipes) appear to be handled offline ("Please
specify bore size when ordering" in the description text) rather than as
separate purchasable SKUs. One ``ScrapedPayload`` per product URL matches
the current model with no lossy pick — this is the invisible-variant case
where the parent page IS the only URL.

Brand strategy: **hybrid pass-through**
---------------------------------------
1. Title heuristic via ``part_manufacturer_from_title`` first (returns e.g.
   ``"JE"`` / ``"Wiseco"`` / ``"Tial"`` for third-party products).
2. House-brand coercion to ``"Buschur Racing"`` when ANY of:
   - the title leads with ``"Buschur"`` / ``"Buschurs"`` / ``"Buschur's"``
     (``'s`` handled case-insensitively; the storefront spells it both ways);
   - the title heuristic picked a car-make / Mitsubishi / Evo / DSM token
     that is clearly NOT the manufacturer. The blocklist covers the
     Mitsubishi-DSM surface: ``mitsubishi``, ``evo``, ``evolution``,
     ``lancer``, ``eclipse``, ``ralliart``, ``galant``, ``dsm`` (+ ``1g``/``2g``
     abbreviations used as title leaders), plus the generic makes that
     could show up in cross-platform kits.
3. If (1) returned a blocklisted / car-make token AND neither the title nor
   the URL indicate house-brand, drop to ``None`` so ingest stores
   ``part_manufacturer_id = NULL`` rather than creating a ``"Mitsubishi"``
   or ``"Evo"`` manufacturer row alongside real brands. Multi-brand
   pass-through — we NEVER blanket-coerce a non-house product to ``"Buschur Racing"``.
4. As a final hint, the SKU suffix (``10170-JE`` → JE, ``10171-WIS`` →
   Wiseco) can upgrade a missing brand; this is a weak signal (the suffix
   is short and ambiguous) so we only map a small known-suffix set.

Discovery
---------
**No XML sitemap.** ``/sitemap.xml``, ``/br-cart/sitemap.xml``, and the
PrestaShop module's conventional ``/1_en_0_sitemap.xml`` all return 404.
The site exposes an HTML "Sitemap" page at ``/br-cart/sitemap`` but it's
just a lightweight page-map, not a product list. We walk the homepage's
left-rail category menu (~211 ``/br-cart/<id>-<slug>`` links covering
the Evo / DSM / Ford / Ralliart trees), then fetch each leaf category
page and collect ``/br-cart/<category-slug>/<id>-<product-slug>.html``
product URLs from it. Categories are small (often 5-30 products each),
so pagination doesn't matter; the default ``n=`` items-per-page value
fits the whole category on one screen. Results are deduplicated on
path. ``CRAWLER_BUSCHURRACING_START_URLS`` (comma-separated) overrides
the discovery with a fixed URL list for smoke tests or targeted re-runs.

Tier rationale
--------------
Plain HTTP works end to end. ``/robots.txt`` and product pages both return
200 to a plain ``Mozilla/5.0`` UA; there is no Cloudflare / Sucuri / JS
challenge. The TLS fingerprint mismatch on the marketing domain
(``buschurracing.com`` not on the cert) is handled by letting ``requests``
follow redirects to the real host, so we don't need Tier 1 impersonation
either.

Caveats
-------
- **Blank SKUs dominate.** Many house-brand items have no
  ``itemprop="sku"`` value. Cross-retailer dedupe will fall back to
  ``retailer + url`` on those rows, same as ``radium``. Do not treat the
  blanks as a scrape failure — they reflect the site's data.
- **Apache 2.2.11 is end-of-life** (released 2009). Occasional 500s or
  connection drops on odd URLs are plausible; the shared retry loop in
  ``fetch_with_retries`` handles transient failures.
- **``buschurracing.com`` SAN mismatch.** The cert CN is
  ``buschursllc.com`` and ``buschurracing.com`` is NOT in the SAN. Python
  ``requests`` follows the 302 to the real host before the final TLS
  handshake (per redirect + connection pool semantics), so verification
  succeeds; bare ``curl`` on the marketing domain needs ``-k`` or to
  target the final host directly.
- **Legacy prices.** The OG ``product:price:amount`` values are integer
  dollar amounts (``"680"`` not ``"680.00"``). ``parse_price_cents`` reads
  those as ``68000`` cents correctly (integer → float → ×100).
"""

import os
import re
import time
from typing import ClassVar, Iterator, List, Optional
from urllib.parse import urljoin, urlparse

from bs4 import BeautifulSoup, Tag

from app.crawlers.adapters.base import RetailerCrawlerAdapter
from app.crawlers.base import (
    DEFAULT_REQUEST_DELAY_SEC,
    ScrapedPayload,
    apply_delay_jitter,
    fetch_page,
)
from app.crawlers.parsing import (
    extract_dom_price,
    extract_part_number_candidate_from_title,
    extract_sku_from_text,
    meta_content,
    normalize_description_text,
    normalize_part_number,
    part_manufacturer_fallback_from_title,
    part_manufacturer_from_description,
    part_manufacturer_from_title,
)

BUSCHUR_BASE = "https://buschursllc.com"
CART_ROOT = BUSCHUR_BASE + "/br-cart/"

# Product URL path shape on PrestaShop: /br-cart/<category-slug>/<id>-<slug>.html
# Category URL path shape:              /br-cart/<id>-<category-slug>
_PRODUCT_PATH_RE = re.compile(r"^/br-cart/[a-z0-9][a-z0-9\-]*/\d+-[a-z0-9][^/]*\.html$", re.IGNORECASE)
_CATEGORY_PATH_RE = re.compile(r"^/br-cart/\d+-[a-z0-9][a-z0-9\-]*/?$", re.IGNORECASE)

# House-brand canonical form and detection patterns. The storefront signs
# products as ``Buschur's ...`` (apostrophe-s) and ``Buschur Racing`` in
# marketing. We canonicalize to ``"Buschur Racing"`` so the manufacturer list
# matches the brand as commonly written.
_HOUSE_BRAND = "Buschur Racing"
_HOUSE_BRAND_TITLE_RE = re.compile(r"^\s*buschur['']?s?\b", re.IGNORECASE)

DEFAULT_START_URLS = [
    # Third-party resale (JE forged pistons) — exercises the pass-through path.
    "https://buschursllc.com/br-cart/pistons-rings/95-je-forged-pistons-101.html",
    # House-brand exhaust — exercises the "Buschur Racing" house-brand coercion.
    "https://buschursllc.com/br-cart/home/2055-buschur-s-1g-dsm-turbo-back-exhaust.html",
]

# Tokens the title heuristic may pick on an Evo / DSM specialist that are
# actually the target vehicle / chassis / engine, not a part manufacturer.
# Dropped to ``None`` so the storefront doesn't grow a ``"Mitsubishi"`` or
# ``"Evo"`` manufacturer row next to real brands. Per-task blocklist.
_TITLE_NON_BRAND_TOKENS = frozenset(
    {
        # Mitsubishi-family / Evo / DSM
        "mitsubishi",
        "mitsu",
        "evo",
        "evolution",
        "lancer",
        "eclipse",
        "ralliart",
        "galant",
        "dsm",
        "1g",
        "2g",
        # Other makes that could appear on cross-platform kits
        "ford",
        "maverick",  # 22+ Ford Maverick line Buschur covers
        "subaru",
        "honda",
        "toyota",
        "nissan",
        "mazda",
        "chevrolet",
        "chevy",
        "evox",
        "evo-x",
        "evoxi",
        # Generic leaders that slip past the shared generic-word set
        "oem",
        "stock",
        "replacement",
        "universal",
    }
)

# SKU-suffix → manufacturer hints. The storefront tags third-party SKUs with
# a short brand code (``-JE`` = JE Pistons, ``-WIS`` = Wiseco). Kept tiny on
# purpose: the suffix is ambiguous (``-JE`` could be a part-code tail), so we
# only upgrade a missing brand — we never override a heuristic-derived one.
_SKU_SUFFIX_BRAND = {
    "JE": "JE Pistons",
    "WIS": "Wiseco",
    "WIS.": "Wiseco",
    "TIAL": "Tial",
    "ARP": "ARP",
}


def _brand_from_sku_suffix(sku: Optional[str]) -> Optional[str]:
    """Return the mapped manufacturer for a ``<prefix>-<SUFFIX>`` SKU shape, else None."""
    if not sku:
        return None
    parts = sku.rsplit("-", 1)
    if len(parts) != 2:
        return None
    suffix = parts[1].strip().upper()
    if not suffix:
        return None
    return _SKU_SUFFIX_BRAND.get(suffix)


def _normalize_part_manufacturer(part_manufacturer: Optional[str]) -> Optional[str]:
    """
    Drop car-make / chassis / platform tokens the title heuristic may pick on
    a Mitsubishi-DSM specialist. Third-party vendor strings (``"JE"``,
    ``"Wiseco"``, ``"Tial"``, ``"AEM"``, …) pass through unchanged so
    re-sold hardware lands on the real manufacturer.
    """
    if not part_manufacturer:
        return part_manufacturer
    brand = part_manufacturer.strip()
    if not brand:
        return None
    if brand.lower() in _TITLE_NON_BRAND_TOKENS:
        return None
    return brand


def _resolve_start_urls() -> List[str]:
    """Env override wins; otherwise discover via homepage category walk, then default."""
    raw = os.environ.get("CRAWLER_BUSCHURRACING_START_URLS", "").strip()
    if raw:
        return [u.strip() for u in raw.split(",") if u.strip()]
    urls = _discover_product_urls_via_categories()
    return urls if urls else list(DEFAULT_START_URLS)


def _is_product_url(url: str) -> bool:
    """True if ``url`` is a Buschur product page on buschursllc.com/br-cart/."""
    try:
        parsed = urlparse(url)
    except ValueError:
        return False
    host = (parsed.hostname or "").lower()
    if host not in ("buschursllc.com", "www.buschursllc.com"):
        return False
    return bool(_PRODUCT_PATH_RE.match(parsed.path or ""))


def _is_category_url(url: str) -> bool:
    """True if ``url`` is a Buschur category page (``/br-cart/<id>-<slug>``)."""
    try:
        parsed = urlparse(url)
    except ValueError:
        return False
    host = (parsed.hostname or "").lower()
    if host not in ("buschursllc.com", "www.buschursllc.com"):
        return False
    return bool(_CATEGORY_PATH_RE.match(parsed.path or ""))


def _discover_product_urls_via_categories() -> List[str]:
    """
    Walk the homepage's category menu to collect every category URL, then fetch
    each category page and harvest product URLs. No XML sitemap exists on this
    store. Categories are small enough (5-30 products each) that pagination
    doesn't matter — the default items-per-page fits the whole category.
    Dedupes on path. Returns an empty list on total network failure.
    """
    category_urls: List[str] = []
    seen_cats: set[str] = set()

    try:
        home_html = fetch_page(CART_ROOT, timeout=20)
    except Exception:
        return []

    home_soup = BeautifulSoup(home_html, "html.parser")
    for a in home_soup.find_all("a", href=True):
        if not isinstance(a, Tag):
            continue
        href = a.get("href")
        if not isinstance(href, str) or not href.strip():
            continue
        abs_url = urljoin(CART_ROOT, href.strip())
        if not _is_category_url(abs_url):
            continue
        # Normalize: strip trailing slash so "/12-evo-789" and "/12-evo-789/" dedupe.
        try:
            parsed = urlparse(abs_url)
        except ValueError:
            continue
        path = (parsed.path or "").rstrip("/")
        key = f"{parsed.hostname}{path}".lower()
        if key in seen_cats:
            continue
        seen_cats.add(key)
        category_urls.append(f"{parsed.scheme}://{parsed.hostname}{path}")

    if not category_urls:
        return []

    seen_products: set[str] = set()
    out: List[str] = []
    for i, cat_url in enumerate(category_urls):
        if i > 0:
            time.sleep(apply_delay_jitter(DEFAULT_REQUEST_DELAY_SEC))
        try:
            cat_html = fetch_page(cat_url, timeout=15)
        except Exception:
            continue
        cat_soup = BeautifulSoup(cat_html, "html.parser")
        for a in cat_soup.find_all("a", href=True):
            if not isinstance(a, Tag):
                continue
            href = a.get("href")
            if not isinstance(href, str) or not href.strip():
                continue
            abs_url = urljoin(cat_url + "/", href.strip())
            # Strip query (add-to-cart links use ?add=1&id_product=… — not product pages)
            base = abs_url.split("?", 1)[0]
            if not _is_product_url(base):
                continue
            try:
                parsed = urlparse(base)
            except ValueError:
                continue
            key = f"{parsed.hostname}{parsed.path}".lower()
            if key in seen_products:
                continue
            seen_products.add(key)
            out.append(base)

    return out


def _normalize_image_url(raw: str) -> Optional[str]:
    """Expand protocol-relative URLs; resolve bare paths against BUSCHUR_BASE."""
    s = raw.strip()
    if not s:
        return None
    if s.startswith("//"):
        return "https:" + s
    if s.startswith("/"):
        return BUSCHUR_BASE + s
    if s.startswith("http://"):
        return "https://" + s[len("http://") :]
    if not s.startswith("http"):
        return None
    return s


def _is_valid_product_image(url: str) -> bool:
    """Keep ``/br-cart/…/<name>.jpg`` product images; reject site chrome."""
    if not url or len(url) < 20:
        return False
    low = url.lower()
    if low.startswith("data:"):
        return False
    if "buschursllc.com" not in low:
        return False
    if re.search(r"logo|favicon|placeholder|sprite|banner|themes/theme|/modules/|/img/icons?/", low):
        return False
    return True


def _extract_gallery_images(soup: BeautifulSoup) -> List[str]:
    """
    Collect product image URLs. PrestaShop serves the hero at
    ``#image-block img`` (``tm_large_default`` size) and thumbnails at
    ``#thumbs_list_frame img`` (``tm_cart_default`` size) — same photo,
    different size. We prefer the large version and ignore the thumbs
    strip when the same filename already appears at large size.
    Capped at 12.
    """
    ordered: List[str] = []
    seen_stems: set[str] = set()

    def _stem(url: str) -> str:
        # Collapse the same photo at different PrestaShop sizes (tm_large_default
        # vs tm_cart_default). File name (last path segment, no query / size
        # directory) is the identity.
        base = url.split("?", 1)[0].rsplit("/", 1)[-1]
        return re.sub(r"\.(jpg|jpeg|png|webp|gif)$", "", base, flags=re.IGNORECASE).lower()

    def add(raw: Optional[str]) -> None:
        if not raw or len(ordered) >= 12:
            return
        normalized = _normalize_image_url(raw)
        if not normalized or not _is_valid_product_image(normalized):
            return
        stem = _stem(normalized)
        if stem and stem in seen_stems:
            return
        seen_stems.add(stem)
        ordered.append(normalized)

    # Primary: hero large image.
    for img in soup.select("#image-block img"):
        if isinstance(img, Tag):
            for attr in ("data-src", "src"):
                v = img.get(attr)
                if isinstance(v, str) and v.strip():
                    add(v)
                    break

    # Secondary: thumbnails (same photo, smaller size — collapsed via stem).
    for img in soup.select("#thumbs_list_frame img, #views_block img"):
        if isinstance(img, Tag):
            for attr in ("data-src", "src"):
                v = img.get(attr)
                if isinstance(v, str) and v.strip():
                    add(v)
                    break

    # OG image fallback.
    if not ordered:
        og = soup.find("meta", property="og:image")
        if isinstance(og, Tag):
            content = meta_content(og)
            if content:
                add(content)

    return ordered[:12]


def _extract_description(soup: BeautifulSoup) -> Optional[str]:
    """
    Description lives inside the product tab's ``<div class="rte">``. Often a
    single sentence on this storefront — keep it when non-trivial.
    """
    for sel in ("#short_description_content", ".rte", "#idTab1 .rte", "[itemprop='description']"):
        el = soup.select_one(sel)
        if not isinstance(el, Tag):
            continue
        text = el.get_text(separator=" ", strip=True)
        if text and len(text) > 10:
            return normalize_description_text(text, max_len=2000)
    og_desc = soup.find("meta", property="og:description")
    if isinstance(og_desc, Tag):
        d = meta_content(og_desc)
        if d and d.strip():
            return normalize_description_text(d, max_len=2000) or d.strip()[:2000]
    meta_desc = soup.find("meta", attrs={"name": "description"})
    if isinstance(meta_desc, Tag):
        d = meta_content(meta_desc)
        if d and d.strip():
            return normalize_description_text(d, max_len=2000) or d.strip()[:2000]
    return None


def _extract_name(soup: BeautifulSoup) -> Optional[str]:
    """
    Product name from ``<h1>`` first (PrestaShop renders it clean), then
    ``og:title`` with the ``" - Buschurs LLC"`` site suffix stripped.
    """
    h1 = soup.find("h1")
    if isinstance(h1, Tag):
        text = h1.get_text(strip=True)
        if text:
            return text
    og = soup.find("meta", property="og:title")
    if isinstance(og, Tag):
        content = meta_content(og)
        if content and content.strip():
            name = content.strip()
            # Strip " - Buschurs LLC" / " - Buschur Racing" trailing site name.
            name = re.sub(r"\s*-\s*Buschur(?:'s|s)?\s*(?:LLC|Racing)\s*$", "", name, flags=re.IGNORECASE)
            return name or None
    return None


def _extract_sku(soup: BeautifulSoup) -> Optional[str]:
    """
    ``<span itemprop="sku">…</span>`` inside ``#product_reference``. Often blank
    on this storefront — we intentionally return None in that case rather than
    invent a SKU.
    """
    el = soup.select_one('#product_reference [itemprop="sku"], [itemprop="sku"]')
    if isinstance(el, Tag):
        text = el.get_text(strip=True)
        if text:
            return text
    return None


class BuschurRacingAdapter(RetailerCrawlerAdapter):
    """
    Buschur Racing (``buschursllc.com/br-cart/``) adapter. Legacy PrestaShop
    storefront, plain HTTP works (no Cloudflare challenge). Discovery walks
    the homepage category menu → each category page collects product URLs
    (no XML sitemap exists). Parsing is microdata + OG-meta + DOM — the page
    has **no JSON-LD**.

    Brand strategy: hybrid pass-through.
    - Title heuristic → third-party manufacturer when the title leads with
      one (``JE``, ``Wiseco``, ``Tial``, …).
    - ``"Buschur Racing"`` house-brand coercion only when the title clearly
      identifies house origin (``Buschur's …``).
    - Car-make / Mitsubishi-DSM / Evo tokens are dropped so we don't mint a
      ``"Mitsubishi"`` or ``"Evo"`` manufacturer row next to real brands.
    - SKU suffix (``-JE``, ``-WIS``) is a last-resort hint when the other
      paths miss.

    SKUs are often blank (house-brand items). We keep the empty value as
    ``None``; cross-retailer dedupe will fall back to ``retailer + url`` on
    those rows, matching the ``radium`` approach.
    """

    ADAPTER_NAME: ClassVar[str] = "buschurracing"
    FETCHER_TIER = "http"

    def discover_product_urls(self) -> Iterator[str]:
        """Yield product URLs from the homepage category walk; env override wins."""
        for url in _resolve_start_urls():
            yield url

    def parse_product_page(self, html: str, url: str) -> Optional[ScrapedPayload]:
        """
        Parse a Buschur Racing product page into a ``ScrapedPayload``. Returns
        ``None`` when the URL isn't product-shaped or the page has no h1 / name.
        """
        if not _is_product_url(url):
            return None

        soup = BeautifulSoup(html, "html.parser")

        name = _extract_name(soup)
        if not name or len(name) < 3:
            return None

        # --- SKU (often blank on this storefront) -------------------------------
        sku_raw = _extract_sku(soup)
        part_number: Optional[str] = normalize_part_number(sku_raw) if sku_raw else None
        if not part_number:
            # Visible sku/part-number patterns in body text (cheap fallback).
            candidate = extract_sku_from_text(soup.get_text())
            if candidate:
                part_number = candidate
        if not part_number:
            # Title-derived part/model code (e.g. ``VF650``). Keeps blank SKUs
            # blank on most Buschur items — their titles rarely contain MPN-like
            # tokens — but recovers the odd page that does.
            part_number = normalize_part_number(extract_part_number_candidate_from_title(str(name)))

        # --- Price --------------------------------------------------------------
        # og:product:price:amount → DOM body regex via shared helper.
        price_cents = extract_dom_price(soup)

        # --- Description -------------------------------------------------------
        description = _extract_description(soup)

        # --- Brand cascade -----------------------------------------------------
        # No microdata brand / manufacturer on this storefront; lean on the
        # title heuristic, then house-brand check, then SKU suffix, then
        # description / fallback.
        part_manufacturer: Optional[str] = _normalize_part_manufacturer(part_manufacturer_from_title(str(name)))
        # House-brand coercion: title starts with ``Buschur`` / ``Buschurs`` /
        # ``Buschur's``. Never applied as a blanket default because that would
        # mis-label the JE / Wiseco / Tial items that share this store.
        if _HOUSE_BRAND_TITLE_RE.match(name or ""):
            part_manufacturer = _HOUSE_BRAND
        # SKU-suffix upgrade only when the other paths missed (low-signal).
        if not part_manufacturer:
            from_sku = _brand_from_sku_suffix(sku_raw)
            if from_sku:
                part_manufacturer = from_sku
        # Description-based hint (covers e.g. "CSF radiator" mentioned inline).
        if not part_manufacturer and description:
            part_manufacturer = _normalize_part_manufacturer(
                part_manufacturer_from_description(description, product_name=str(name))
            )
        # Shared known-pattern fallback (VF-Engineering and friends).
        if not part_manufacturer:
            part_manufacturer = _normalize_part_manufacturer(part_manufacturer_fallback_from_title(str(name)))

        # --- Images ------------------------------------------------------------
        image_urls = _extract_gallery_images(soup) or None

        return ScrapedPayload(
            name=str(name),
            product_url=url,
            description=description if description else None,
            price_cents=price_cents,
            part_manufacturer=part_manufacturer,
            part_number=part_number,
            image_urls=image_urls,
        )
